// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=none"
// @generated from file example/v1/example.proto (package example.v1, syntax proto3)
/* eslint-disable */

import type {Message} from '@bufbuild/protobuf'
import type {GenFile, GenMessage, GenService} from '@bufbuild/protobuf/codegenv1'
import {fileDesc, messageDesc, serviceDesc} from '@bufbuild/protobuf/codegenv1'

/**
 * Describes the file example/v1/example.proto.
 */
export const file_example_v1_example: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChhleGFtcGxlL3YxL2V4YW1wbGUucHJvdG8SCmV4YW1wbGUudjEiIQoRSGVsbG9VbmFyeVJlcXVlc3QSDAoEbmFtZRgBIAEoCSImChJIZWxsb1VuYXJ5UmVzcG9uc2USEAoIZ3JlZXRpbmcYASABKAkiKAoYSGVsbG9DbGllbnRTdHJlYW1SZXF1ZXN0EgwKBG5hbWUYASABKAkiLQoZSGVsbG9DbGllbnRTdHJlYW1SZXNwb25zZRIQCghncmVldGluZxgBIAEoCSIoChhIZWxsb1NlcnZlclN0cmVhbVJlcXVlc3QSDAoEbmFtZRgBIAEoCSItChlIZWxsb1NlcnZlclN0cmVhbVJlc3BvbnNlEhAKCGdyZWV0aW5nGAEgASgJIiYKFkhlbGxvQmlEaVN0cmVhbVJlcXVlc3QSDAoEbmFtZRgBIAEoCSIrChdIZWxsb0JpRGlTdHJlYW1SZXNwb25zZRIQCghncmVldGluZxgBIAEoCTKFAwoORXhhbXBsZVNlcnZpY2USSwoKSGVsbG9VbmFyeRIdLmV4YW1wbGUudjEuSGVsbG9VbmFyeVJlcXVlc3QaHi5leGFtcGxlLnYxLkhlbGxvVW5hcnlSZXNwb25zZRJiChFIZWxsb0NsaWVudFN0cmVhbRIkLmV4YW1wbGUudjEuSGVsbG9DbGllbnRTdHJlYW1SZXF1ZXN0GiUuZXhhbXBsZS52MS5IZWxsb0NsaWVudFN0cmVhbVJlc3BvbnNlKAESYgoRSGVsbG9TZXJ2ZXJTdHJlYW0SJC5leGFtcGxlLnYxLkhlbGxvU2VydmVyU3RyZWFtUmVxdWVzdBolLmV4YW1wbGUudjEuSGVsbG9TZXJ2ZXJTdHJlYW1SZXNwb25zZTABEl4KD0hlbGxvQmlEaVN0cmVhbRIiLmV4YW1wbGUudjEuSGVsbG9CaURpU3RyZWFtUmVxdWVzdBojLmV4YW1wbGUudjEuSGVsbG9CaURpU3RyZWFtUmVzcG9uc2UoATABYgZwcm90bzM',
  )

/**
 * @generated from message example.v1.HelloUnaryRequest
 */
export type HelloUnaryRequest = Message<'example.v1.HelloUnaryRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string
}

/**
 * Describes the message example.v1.HelloUnaryRequest.
 * Use `create(HelloUnaryRequestSchema)` to create a new message.
 */
export const HelloUnaryRequestSchema: GenMessage<HelloUnaryRequest> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 0)

/**
 * @generated from message example.v1.HelloUnaryResponse
 */
export type HelloUnaryResponse = Message<'example.v1.HelloUnaryResponse'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message example.v1.HelloUnaryResponse.
 * Use `create(HelloUnaryResponseSchema)` to create a new message.
 */
export const HelloUnaryResponseSchema: GenMessage<HelloUnaryResponse> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 1)

/**
 * @generated from message example.v1.HelloClientStreamRequest
 */
export type HelloClientStreamRequest = Message<'example.v1.HelloClientStreamRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string
}

/**
 * Describes the message example.v1.HelloClientStreamRequest.
 * Use `create(HelloClientStreamRequestSchema)` to create a new message.
 */
export const HelloClientStreamRequestSchema: GenMessage<HelloClientStreamRequest> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 2)

/**
 * @generated from message example.v1.HelloClientStreamResponse
 */
export type HelloClientStreamResponse = Message<'example.v1.HelloClientStreamResponse'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message example.v1.HelloClientStreamResponse.
 * Use `create(HelloClientStreamResponseSchema)` to create a new message.
 */
export const HelloClientStreamResponseSchema: GenMessage<HelloClientStreamResponse> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 3)

/**
 * @generated from message example.v1.HelloServerStreamRequest
 */
export type HelloServerStreamRequest = Message<'example.v1.HelloServerStreamRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string
}

/**
 * Describes the message example.v1.HelloServerStreamRequest.
 * Use `create(HelloServerStreamRequestSchema)` to create a new message.
 */
export const HelloServerStreamRequestSchema: GenMessage<HelloServerStreamRequest> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 4)

/**
 * @generated from message example.v1.HelloServerStreamResponse
 */
export type HelloServerStreamResponse = Message<'example.v1.HelloServerStreamResponse'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message example.v1.HelloServerStreamResponse.
 * Use `create(HelloServerStreamResponseSchema)` to create a new message.
 */
export const HelloServerStreamResponseSchema: GenMessage<HelloServerStreamResponse> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 5)

/**
 * @generated from message example.v1.HelloBiDiStreamRequest
 */
export type HelloBiDiStreamRequest = Message<'example.v1.HelloBiDiStreamRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string
}

/**
 * Describes the message example.v1.HelloBiDiStreamRequest.
 * Use `create(HelloBiDiStreamRequestSchema)` to create a new message.
 */
export const HelloBiDiStreamRequestSchema: GenMessage<HelloBiDiStreamRequest> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 6)

/**
 * @generated from message example.v1.HelloBiDiStreamResponse
 */
export type HelloBiDiStreamResponse = Message<'example.v1.HelloBiDiStreamResponse'> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string
}

/**
 * Describes the message example.v1.HelloBiDiStreamResponse.
 * Use `create(HelloBiDiStreamResponseSchema)` to create a new message.
 */
export const HelloBiDiStreamResponseSchema: GenMessage<HelloBiDiStreamResponse> =
  /*@__PURE__*/
  messageDesc(file_example_v1_example, 7)

/**
 * @generated from service example.v1.ExampleService
 */
export const ExampleService: GenService<{
  /**
   * @generated from rpc example.v1.ExampleService.HelloUnary
   */
  helloUnary: {
    methodKind: 'unary'
    input: typeof HelloUnaryRequestSchema
    output: typeof HelloUnaryResponseSchema
  }
  /**
   * @generated from rpc example.v1.ExampleService.HelloClientStream
   */
  helloClientStream: {
    methodKind: 'client_streaming'
    input: typeof HelloClientStreamRequestSchema
    output: typeof HelloClientStreamResponseSchema
  }
  /**
   * @generated from rpc example.v1.ExampleService.HelloServerStream
   */
  helloServerStream: {
    methodKind: 'server_streaming'
    input: typeof HelloServerStreamRequestSchema
    output: typeof HelloServerStreamResponseSchema
  }
  /**
   * @generated from rpc example.v1.ExampleService.HelloBiDiStream
   */
  helloBiDiStream: {
    methodKind: 'bidi_streaming'
    input: typeof HelloBiDiStreamRequestSchema
    output: typeof HelloBiDiStreamResponseSchema
  }
}> = /*@__PURE__*/ serviceDesc(file_example_v1_example, 0)
